# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env

networks:
  default: development
  development:
    cmd_settings:
      mnemonic: brownie
      default_balance: 100000000000000000000

    update_interval: 60
    verify: False

  goerli-fork-dev:
    default_balance: 100000000000000000000

# enable output of development artifacts to load with react
dev_deployment_artifacts: true

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  - safe-global/safe-contracts@1.3.0-libs.0

compiler:
  evm_version: null
  solc:
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - '@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.5.0/contracts/'
      - '@safe-global/safe-contracts/contracts=safe-global/safe-contracts@1.3.0-libs.0/contracts/'
    version: 0.8.12